export {default as Navbar} from './Navbar/Navbar';
export {default as Header} from './Header/Header';
export {default as Shop} from './Shop/Shop';
export {default as Save} from './Save/Save';
export {default as See} from './See/See';
export {default as Ideas} from './Ideas/Ideas';
export {default as Form} from './Form/Form';
export {default as Contact} from './Contact/Contact';
export {default as Footer} from './Footer/Footer';